version: "3.8"

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - 5004:8080

  node-server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    environment:
      - APP_PORT=8080
    ports:
      - 5005:8080
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "5006:3306"
    volumes:
      - ./db:/var/lib/mysql
