version: "3.8"

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - api
      - client
    restart: always
    ports:
      - "3050:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  api:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    ports:
      - 5005:8080
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env
    ports:
      - "5006:3306"
    volumes:
      - ./db:/var/lib/mysql

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
