version: "3.8"

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5004:8080
    depends_on:
      - node-server

  node-server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_PORT=${NODE_PORT}
    ports:
      - 5005:8080
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "5006:3306"
    volumes:
      - ./db:/var/lib/mysql
